### ISSUE TITLE
Request for Code for Searching Strategy Implementation

### ISSUE THREAD

**Issue by 1999Lyd** [ywh187/FitPrune#1]
Hi,
Thank you for the fantastic work! I would love to implement your algorithm on a custom dataset and model, but I wasn't able to find the code related to the searching strategy. Could you kindly provide the code for the search algorithm or share some guidelines on how to implement it from scratch? Thank you!

**Comment by yuanrr** [comment]
+1.  I am very interested and looking forward to a quick start/ guidance for your work!

**Comment by ywh187** [comment]
Hello! We have included the code for statistical analysis, and you can find the usage instructions in the README.md file. Please take a look.

**Comment by SherrySwift** [comment]
> Hello! We have included the code for statistical analysis, and you can find the usage instructions in the README.md file. Please take a look.

Hi, Could you also kindly provide the statistical_analysis_data.jsonl that you used for statistical analysis? Thank you!
