### ISSUE TITLE
Questions about KVCache

### ISSUE THREAD

**Issue by RuixiWanggg** [ywh187/FitPrune#3]
Thank you for the excellent work, I find it very intriguing. I'm curious to know if FitPrune can utilize KVCache during its operation. If so, would leveraging KVCache help accelerate the inference process effectively?

**Comment by ywh187** [comment]
Hello, thank you for your interest! 
FitPrune operates during the pre-filling stage. As token pruning at each layer, the KV Cache is significantly reduced compared to the original version. This reduction in KV Cache leads to faster speeds during the generation phase.
