### ISSUE TITLE
Question on `statistical data` in Table 3

### ISSUE THREAD

**Issue by SCZwangxiao** [ywh187/FitPrune#4]
Thank you for the open source! 

I am quite confused with the `statistical data` in Table 3.

In Table 3, different number of samples are ablated, which means that the algorithm will calculate some dataset statistics (of the attention weight). However, in the `Method` section, it seems that the `FitPrune` `algorithm 1` is running on a single sample. How does the `Algorithm 1` correlate to the dataset statistics?

There seems to be a conflict, or is there anything I misunderstood?

**Comment by ywh187** [comment]
Hi, I'm sorry for causing your confusion. In Algorithm 1, we perform the statistics on a batch of data (similar to batch inference). 

For different examples, at each layer of the model, the total attention weight of the visual tokens follows a relatively fixed pattern. However, each individual example may have certain deviations. Therefore, we need to conduct statistics on a batch of data to obtain a stable pruning strategy.
