### ISSUE TITLE
apply fitprune on another MLLM

### ISSUE THREAD

**Issue by SKY072410** [ywh187/FitPrune#5]
I would like to ask, if I want to apply this method to other multimodal large models, what code would need to be rewritten?Thank you for your reply!

**Comment by ywh187** [comment]
Hello. The code mainly consists of two parts: statistical analysis and inference. We provide an example for **LLaVA 1.5** that you can refer to. Specifically for the statistical part, you can check `llava/eval/statistical_analysis.py`. For instance, you'll need to set the number of layers and feature dimensions for your model. Additionally, you can replace the statistical data with the training set of your model. 
I hope this helps.
